name: hw2_drq_new
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - nvidia::cudatoolkit=10.1
  - pytorch::pytorch
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - "gym[atari]==0.19.0"
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - hydra-core==0.11.3
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - sklearn
    - matplotlib
    - kornia
    - wandb
